setwd("C:\\Users\\_lxy\\Desktop\\cygwin\\sctp_simulation")
library(ggplot2)
delay<-read.table("output/delay1")
g<-ggplot(data=delay,aes(x=V1,y=V2))
graph_delay<-g+geom_point(color="darkblue",alpha=0.1)+labs(title="End-end delay",x="simulation time(s)",y="delay time(s)")
