setwd("C:\\Users\\_lxy\\Desktop\\cygwin\\sctp_simulation")
library(ggplot2)
th<-read.table("output/sctp_r_th")
colnames(th)<-c("time","throughput","direction")
g<-ggplot(data=th,aes(x=time,y=throughput))
graph_all<-g+geom_point(aes(color=direction),alpha=0.6)+labs(title="average throughput",x="time(s)",y="throughput(kb/s)")+geom_smooth()
graph_sub<-g+geom_point(aes(color=direction),alpha=0.7)+facet_wrap(~direction,scales ="free")+labs(title="average throughput",x="time(s)",y="throughput(kb/s)")+theme(legend.position="none")
g<-ggplot(data=th,aes(x=time))
graph_fre<-g+geom_histogram(aes(fill=direction),alpha=0.5,binwidth=0.4)+labs(title="number of packets",x="time(s)",y="packets")