BEGIN{
	init=0;
	i=0;
}
{
	action=$1;
	time=$2;
	node_1=$3;
	node_2=$4;
	src=$5;
	pktsize=$6
	flow_id=$8;
	node_1_address=$9;
	node_2_address=$10;
	seq_no=$11;
	packet_id=$12;
	if(action=="r"){
	pkt_byte_sum[i+1]=pkt_byte_sum[i]+pktsize;
	node1[i+1]=node_1;
	node2[i+1]=node_2;
	if(init==0){
		start_time=time;
		init=1;
	}
	end_time[i]=time;
	i=i+1;
	}
}
END{
	printf("%.2f\t%.2f\t%d-%d\n",end_time[0],0,node1[1],node2[1]);
	#printf("%d",i)
	for(j=1;j<i;j++){
		th=pkt_byte_sum[j]/(end_time[j]-start_time)*8/1000;
		printf("%.2f\t%.2f\t%d-%d\n",end_time[j],th,node1[j],node2[j]);
	}
}